spring.application.name=currency-exchange
spring.config.import=optional:configserver:http://localhost:8888

# R2DBC Configuration
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.h2.console.enabled=true

# Show SQL for R2DBC
logging.level.org.springframework.r2dbc=DEBUG

# Initialize Database from schema.sql and data.sql
spring.jpa.defer-datasource-initialization=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
resilience4j.retry.instances.sample-api.maxAttempts=5 
resilience4j.retry.instances.sample-api.waitDuration=500ms
resilience4j.retry.instances.sample-api.enableExponentialBackoff=true

# CircuitBreaker properties
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.default.failureRateThreshold=50

# RateLimiter properties
resilience4j.ratelimiter.instances.default.limitForPeriod=2
resilience4j.ratelimiter.instances.default.limitRefreshPeriod=10s

resilience4j.bulkhead.instances.default.maxConcurrentCalls=2
